# Site settings
title: test
email: frances.mojica@outlook.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "francesmjc.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
